var gulp = require('gulp');
var useref = require('gulp-useref');
var replace = require('gulp-replace');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var cleanCSS = require('gulp-clean-css');
var htmlmin = require('gulp-htmlmin');
var inlinesource = require('gulp-inline-source');

//MAKE ONE FILE JS
gulp.task('make-one-js', function () {
	return gulp.src(['uncompress/js/variable.js', 'uncompress/js/common.js', 'uncompress/js/video.js','uncompress/js/slide.js', 'uncompress/js/load.js', 'uncompress/js/btq.js'])
		.pipe(uglify())
		.pipe(concat('app.js'))
		.pipe(gulp.dest('js'));

});


//MAKE ONE FILE CSS
gulp.task('make-one-css', function () {
	return gulp.src(['uncompress/css/images.css', 'uncompress/css/animation.css'])
		.pipe(cleanCSS({
			zindex: false,
			reduceIdents: false,
			autoprefixer: {
				remove: false
			},
			discardComments: {
				removeAll: true
			},
			discardUnused: false,
			colormin: false,
		}))
		.pipe(concat('app.css'))
		.pipe(gulp.dest('css'));

});


//COMPRESS OTHER CSS
gulp.task('compress-css', function () {
	return gulp.src(['uncompress/css/header.css', 'uncompress/css/slide.css', 'uncompress/css/style.css'])
		.pipe(cleanCSS({
			zindex: false,
			reduceIdents: false,
			autoprefixer: {
				remove: false
			},
			discardComments: {
				removeAll: true
			},
			discardUnused: false,
			colormin: false,
		}))
		.pipe(concat('header.css'))
		.pipe(gulp.dest('css'));

});


//COMPRESS OTHER JS AND CSS
gulp.task('compress-js', function () {
	return gulp.src(['uncompress/js/gsap.js'])
		.pipe(uglify())
		.pipe(gulp.dest('js'));
});


//HTML MOVE
gulp.task('move-html', function () {
	return gulp.src('uncompress/htmls/*.html')
		.pipe(useref())
		.pipe(gulp.dest('htmls'));
});


//INLINE CSS HEADER
var AppendCSS = function AppendCSS() {
	setTimeout(function () { inLine(); }, 1000);
	return gulp.src(['htmls/*.html'])
		.pipe(inlinesource())
		.pipe(gulp.dest("htmls"));
}


//HTML COMPRESS
var inLine = function inLine() {
	setTimeout(function () { getPathEnd(); }, 1000);
	return gulp.src('htmls/*.html')
		//.pipe(htmlmin({ collapseWhitespace: true, removeComments: true, includeAutoGeneratedTags: false }))
		.pipe(gulp.dest('htmls'));
};



gulp.task('inline-html', function () {
	setTimeout(function () { getPathEnd(); }, 1000);
	return gulp.src('htmls/*.html')
		//.pipe(htmlmin({ collapseWhitespace: true, removeComments: true, includeAutoGeneratedTags: false }))
		.pipe(gulp.dest('htmls'));
});



//REPLACE PATH END
var getPathEnd = function getpathEnd() {
	return gulp.src('htmls/*.html')
		.pipe(replace('<script src="../js/app.js" type="text/javascript"></script>', '<script src="../js/app.js" type="text/javascript"></script></body></html>'))
		.pipe(gulp.dest('htmls'));
};


//MAIN TASK
gulp.task('compress', gulp.series('move-html', 'make-one-js', 'make-one-css', 'compress-css', 'compress-js', function (done) {
	AppendCSS();
	done();
}));


//COMPRESS CSS
gulp.task('css', gulp.series('move-html', 'make-one-css', 'compress-css', function (done) {
	AppendCSS();
	done();
}));


//COMPRESS JS
gulp.task('js', gulp.series('make-one-js'));


//EDIT HTML
gulp.task('html', gulp.series('move-html', function (done) {
	AppendCSS();
	done();
}));
